Notepad
RomE-HK/java-at-lessons pull request #3
Opened 2019-02-24 14:36 UTC by RomE-HK

Now at least something is working

2019-02-25 21:36 UTC, AnnaS91 requested changes

2019-02-25 21:36 UTC, AnnaS91 commented on notepad/src/epam/rome/NotepadRecord.java
> +    public void ShowRecord() {
1) методы называем всегда с маленькой буквы, чтобы отличать от конструкторов
2) Вы можете переопределить метод toString, в котором будете собирать текст (можно, например, через String.format или через StringBuilder), а уже в методе showRecord просто вызвать System.out.println(this); и он сам обратится к методу toString() и всё Вам отобразит

2019-02-25 21:36 UTC, AnnaS91 commented on notepad/src/epam/rome/NotepadRecord.java
> +
здесь ещё напрашивается метод по редактированию, когда у вас при изменении title или text будет апдейтиться дата автоматически

2019-02-25 21:36 UTC, AnnaS91 commented on notepad/src/epam/rome/Notepad.java
> +        allNotes = new NotepadRecord[32];
32 - magic number. Все такие числа лучше выносить в константы класса, которые при необходимости будет легко поменять

2019-02-25 21:36 UTC, AnnaS91 commented on notepad/src/epam/rome/Notepad.java
> +    Notepad() {
а почему дефолтный модификатор доступа?

2019-02-25 21:36 UTC, AnnaS91 commented on notepad/src/epam/rome/Notepad.java
> +    public void setNote(NotepadRecord note) {
всё-таки название "set..." чаще используют для установки полей класса, лучше addNote

2019-02-25 21:36 UTC, AnnaS91 commented on notepad/src/epam/rome/Notepad.java
> +    public void getNote(int noteNumber) {
1) странно, что метод getNote ничего не возвращает. Логичнее было бы возвращать найденный note. 
2) А что произойдет с программой, если передать неправильный индекс? По-хорошему, обработка таких кейсов - задача Вашего метода

2019-02-27 08:45 UTC, RomE-HK commented on notepad/src/epam/rome/NotepadRecord.java
> +    public void ShowRecord() {
1. Да, точно. Писал спросоня)
Поправил
2. Спасибо за наводку. Метод переопределил, но пока не написал реализацию

2019-02-27 08:47 UTC, RomE-HK commented on notepad/src/epam/rome/NotepadRecord.java
> +
Методы по редактированию добавил

2019-02-27 08:48 UTC, RomE-HK commented on notepad/src/epam/rome/Notepad.java
> +        allNotes = new NotepadRecord[32];
Спасибо, поправил. Вынес в константу класса

2019-02-27 08:53 UTC, RomE-HK commented on notepad/src/epam/rome/Notepad.java
> +    Notepad() {
Я изначально собирался сделать конструктор приватным, чтобы можно было иметь лишь один экземпляр Блокнота. Но потом подумал, что почему бы не иметь возможность работы с несколькими отдельными блокнотами, и оставил дефолтный модификатор. И убрал static у notesCount

2019-02-27 08:54 UTC, RomE-HK commented on notepad/src/epam/rome/Notepad.java
> +    public void setNote(NotepadRecord note) {
Поправил

2019-02-27 09:00 UTC, RomE-HK commented on notepad/src/epam/rome/Notepad.java
> +    public void getNote(int noteNumber) {
1. Поправил и добавил метод showNote. Теперь getNote именно возвращает экземпляр записи, а showNote позволяет вывести запись на экран
2. До обработки пограничных условий и неверных входных данных пока не добрался, но помню про них. Спасибо

2019-02-27 09:20 UTC, RomE-HK reviewed
Ответил на комментарии и написал пару вопросов

2019-02-27 09:20 UTC, RomE-HK commented on notepad/src/epam/rome/Notepad.java
> -    private void resizeArray() {
Перенесён в конец списка методов, т.к. приватный

2019-02-27 09:20 UTC, RomE-HK commented on notepad/src/epam/rome/NotepadRecord.java
> -    private Date dateUpdate() {
Перенесён в конец списка методов, т.к. приватный

2019-02-27 09:20 UTC, RomE-HK commented on notepad/src/epam/rome/Notepad.java
> +            allNotes[notesCount - 1].replaceRecord(null);
2) Либо непосредственно изменять уже содержащуюся запись с помощью метода, который обращается к полям

Правда, если я всё правильно понял, то передав в метод null я в итоге получу NullPointerException? Так как в методе идёт обращение к полям объекта, которых у null'а нет да и объектом он не является.
Пока пришёл в голову вариант с перегрузкой метода replaceRecord() без аргументов, который будет поля дефолтными значениями забивать. Но мне почему-то кажется, что я всё усложняю)

2019-02-27 09:20 UTC, RomE-HK commented on notepad/src/epam/rome/Notepad.java
> +            // allNotes[notesCount - 1] = null;
Вот про это я вчера спрашивал.
1) Есть вариант записи в массиве просто присваивать ссылку на другой объект

2019-03-18 20:49 UTC, AnnaS91 requested changes

2019-03-18 20:49 UTC, AnnaS91 commented on notepad/src/main/java/epam/rome/notepad/model/NotepadRecord.java
> +        title = "Default";
1) раз строка встречается дважды, уже можно подумать о том, чтобы вынести её в константу класса
2) здесь можно было бы вызвать второй конструктор, просто передав ему 2 дефолтных строки

2019-03-18 20:49 UTC, AnnaS91 commented on notepad/src/main/java/epam/rome/notepad/model/NotepadRecord.java
> +        SimpleDateFormat formatForFate = new SimpleDateFormat("dd.MM.yyyy kk:mm:ss");
👍

2019-03-18 20:49 UTC, AnnaS91 commented on notepad/src/main/java/epam/rome/notepad/model/Notepad.java
> +        if (title.length() > 0 || text.length() > 0) {
1) можно использовать isEmpty()
2) возможно стоит добавить проверки на null

2019-03-18 20:49 UTC, AnnaS91 commented on notepad/src/main/java/epam/rome/notepad/model/Notepad.java
> +            // Как вернуть не null? Только новая запись? Тогда получается она взялась ниоткуда
а чем плохо вернуть здесь null?

2019-03-18 20:49 UTC, AnnaS91 commented on notepad/src/main/java/epam/rome/notepad/model/Notepad.java
> +    public void delNote(int noteIndex) {
не сокращай слова, deleteNote

2019-03-18 20:49 UTC, AnnaS91 commented on notepad/src/main/java/epam/rome/notepad/model/Notepad.java
> +    public void showAllNotes() {
всё таки раз ты удаляешь записи, перемешивая их индексы, возможно стоило бы их показывать отсортированными по датам

2019-03-18 20:49 UTC, AnnaS91 commented on notepad/src/main/java/epam/rome/notepad/model/Notepad.java
> +        Arrays.sort(allNotes, Comparator.comparing(NotepadRecord::getDate));
👍

2019-03-20 12:35 UTC, RomE-HK commented on notepad/src/main/java/epam/rome/notepad/model/NotepadRecord.java
> +        title = "Default";
Сделал

2019-03-20 12:35 UTC, RomE-HK commented on notepad/src/main/java/epam/rome/notepad/model/Notepad.java
> +    public void delNote(int noteIndex) {
Поправил

2019-03-20 12:38 UTC, RomE-HK commented on notepad/src/main/java/epam/rome/notepad/model/Notepad.java
> +        if (title.length() > 0 || text.length() > 0) {
Нашёл интересный вариант проверки на пустую строку, состоящую только из пробелов и null. Чуть позже запушу

2019-03-20 12:40 UTC, RomE-HK commented on notepad/src/main/java/epam/rome/notepad/model/Notepad.java
> +            // Как вернуть не null? Только новая запись? Тогда получается она взялась ниоткуда
У меня есть конструкция вида
`pad.getNote(noteToChange).changeTitle(text)`
в Main'е, но я так понимаю, стоит её просто разбить на две части и проверять не null ли вернулся?

2019-03-20 12:43 UTC, RomE-HK commented on notepad/src/main/java/epam/rome/notepad/model/Notepad.java
> +    public void showAllNotes() {
Хм, а это мысль. Я как раз не хотел добавлять сортировку после каждого удаления, т.к. в ней тогда смысла бы не было, но и куда добавить её я пока не знал.

2019-03-20 12:49 UTC, AnnaS91 commented on notepad/src/main/java/epam/rome/notepad/model/Notepad.java
> +            // Как вернуть не null? Только новая запись? Тогда получается она взялась ниоткуда
абсолютно верно

2019-03-20 14:16 UTC, RomE-HK commented on notepad/src/main/java/epam/rome/notepad/model/Notepad.java
> +        Arrays.sort(allNotes, Comparator.comparing(NotepadRecord::getDate));
На самом деле, оно почему-то не работало - выпадал NPF. Сейчас изменил и вроде даже сортирует)

2019-03-20 14:20 UTC, RomE-HK commented on notepad/src/main/java/epam/rome/notepad/model/Notepad.java
> +    public void showAllNotes() {
Спасибо. Прикрутил вызов сортировки

2019-03-20 14:49 UTC, RomE-HK commented on notepad/src/main/java/epam/rome/notepad/model/Notepad.java
> +            // Как вернуть не null? Только новая запись? Тогда получается она взялась ниоткуда
Готово

2019-03-20 17:21 UTC, AnnaS91 approved these changes

2019-03-21 09:51 UTC, merged