ByteIO
RomE-HK/java-at-lessons pull request #4
Opened 2019-03-26 21:44 UTC by RomE-HK

All code is written, but no test for now

2019-03-28 17:11 UTC, AnnaS91 approved these changes

2019-03-28 17:11 UTC, AnnaS91 commented on byteIO/src/main/java/epam/rome/byteio/ByteIOFindKeyWords.java
> +    public static void readFile(Map<String, Integer> map, String filePath) {
не согласна с названием метода, Вы же не просто читаете файл, Вы его анализируете и модифицируете переданный map

2019-04-13 21:08 UTC, AnnaS91 requested changes

2019-04-13 21:08 UTC, AnnaS91 commented on byteIO/src/main/java/epam/rome/byteio/ByteIOFindKeyWords.java
> +        System.out.println("Keywords successfully got");
а ведь если была выкинута ошибка, ты её перехватишь, а пользователю всё равно выведешь, что keywords найдены успешно, хотя это противоречит фактам. Сдается мне, что эта строка должна быть в try.

2019-04-13 21:08 UTC, AnnaS91 commented on byteIO/src/main/java/epam/rome/byteio/ByteIOFindKeyWords.java
> +        System.out.println("Matches successfully found");
аналогично предыдущему замечанию, только я бы из catch ещё и false возвращала

2019-04-13 21:08 UTC, AnnaS91 commented on byteIO/src/main/java/epam/rome/byteio/ByteIOFindKeyWords.java
> +        System.out.println("Matches successfully wrote to file");
и тут тоже

2019-04-13 21:08 UTC, AnnaS91 commented on byteIO/src/test/java/epam/rome/byteio/ByteIOFindKeyWordsTest.java
> +    public static void cleanUp() {
в целом можно не чистить объекты руками. Вот если бы это было обращение к базе данных или Вы бы хотели удалить какие-то созданные тестовые файлы, это можно было бы сделать в этом методе

2019-04-13 21:08 UTC, AnnaS91 commented on byteIO/src/test/java/epam/rome/byteio/ByteIOFindKeyWordsTest.java
> +            assertTrue(testMap.get("void") != 0);
а почему не проверить через assetEquals, сравнив с числом? оно же у вас не меняется

2019-04-13 21:08 UTC, AnnaS91 commented on byteIO/src/test/java/epam/rome/byteio/ByteIOFindKeyWordsTest.java
> +
можно было бы добавить ещё тесты для специфичных кейсов - слипшихся слов (privatepublic), частей слов (int1, 1int, print)

2019-04-14 14:23 UTC, RomE-HK commented on byteIO/src/main/java/epam/rome/byteio/ByteIOFindKeyWords.java
> +    public static void readFile(Map<String, Integer> map, String filePath) {
Fixed

2019-04-14 14:25 UTC, RomE-HK commented on byteIO/src/main/java/epam/rome/byteio/ByteIOFindKeyWords.java
> +        System.out.println("Keywords successfully got");
Упс! Действительно)

2019-04-14 14:25 UTC, RomE-HK commented on byteIO/src/test/java/epam/rome/byteio/ByteIOFindKeyWordsTest.java
> +    public static void cleanUp() {
Понял, учту. Просто думал, что ресурсы стоит высвобождать сразу

2019-04-14 14:27 UTC, RomE-HK commented on byteIO/src/test/java/epam/rome/byteio/ByteIOFindKeyWordsTest.java
> +
Но в целом нас интересуют, как я понимаю, только учёт слов не слипшихся?

2019-04-14 15:23 UTC, AnnaS91 commented on byteIO/src/test/java/epam/rome/byteio/ByteIOFindKeyWordsTest.java
> +
Да, просто проверить, что они не засчитываются у тебя

2019-04-15 13:03 UTC, RomE-HK commented on byteIO/src/main/java/epam/rome/byteio/ByteIOFindKeyWords.java
> +        System.out.println("Matches successfully found");
Но если мы возвращаем false в catch, то сообщение можно ведь на месте оставить. Ведь если мы свалимся в catch, то оттуда путь уже только из метода.

2019-04-15 13:04 UTC, RomE-HK commented on byteIO/src/main/java/epam/rome/byteio/ByteIOFindKeyWords.java
> +        System.out.println("Keywords successfully got");
Fixed

2019-04-15 13:18 UTC, RomE-HK commented on byteIO/src/test/java/epam/rome/byteio/ByteIOFindKeyWordsTest.java
> +            assertTrue(testMap.get("void") != 0);
А если я просто тут впишу это число, это разве не будет Magic Number?

2019-04-15 13:58 UTC, AnnaS91 commented on byteIO/src/main/java/epam/rome/byteio/ByteIOFindKeyWords.java
> +        System.out.println("Matches successfully found");
да, конечно, сообщение нужно оставить

2019-04-15 13:59 UTC, AnnaS91 commented on byteIO/src/test/java/epam/rome/byteio/ByteIOFindKeyWordsTest.java
> +            assertTrue(testMap.get("void") != 0);
это же тесты, в них можно использовать любые числа и строки

2019-04-15 14:27 UTC, RomE-HK commented on byteIO/src/main/java/epam/rome/byteio/ByteIOFindKeyWords.java
> +        System.out.println("Matches successfully found");
Ready

2019-04-15 14:27 UTC, RomE-HK commented on byteIO/src/main/java/epam/rome/byteio/ByteIOFindKeyWords.java
> +        System.out.println("Matches successfully wrote to file");
Ready

2019-04-15 14:28 UTC, RomE-HK commented on byteIO/src/test/java/epam/rome/byteio/ByteIOFindKeyWordsTest.java
> +
Fixed

2019-04-15 14:32 UTC, RomE-HK commented on byteIO/src/test/java/epam/rome/byteio/ByteIOFindKeyWordsTest.java
> +    private static String testClassFilePath;
Поменял тут имя переменной, а то сам запутался это "TestFile Path" или "Test FilePath"

2019-04-17 14:47 UTC, AnnaS91 requested changes

2019-04-17 14:47 UTC, AnnaS91 commented on byteIO/src/main/java/epam/rome/byteio/ByteIOFindKeyWords.java
> +        String[] words = str.split(" ");
при таком способе деления мы скорее всего пропустим break; (из-за точки с запятой)
добавь, пожалуйста, тест на это

2019-04-17 15:19 UTC, RomE-HK commented on byteIO/src/main/java/epam/rome/byteio/ByteIOFindKeyWords.java
> +        String[] words = str.split(" ");
Хм. Тогда и return; тоже может быть пропущен, если будет в коде.
Сейчас займусь

2019-04-17 21:38 UTC, RomE-HK commented on byteIO/src/main/java/epam/rome/byteio/ByteIOFindKeyWords.java
> +        String[] words = str.split(" ");
Посидел подумал и внезапно осознал, что при разделении лишь пробелами, теряется ОЧЕНЬ много кейсов и помимо break;
Как то, (new или try{
Добавил в split дополнительных разделителей

2019-04-18 11:31 UTC, AnnaS91 approved these changes
Зачтено!

2019-04-18 11:31 UTC, AnnaS91 commented on byteIO/src/main/java/epam/rome/byteio/ByteIOFindKeyWords.java
> +        String[] words = str.trim().split("\\s+|\\t|\\;|\\(|\\)|\\{|\\}|\\[|\\]");
Отлично. В целом так как мы точно проверяем слова без цифр, мы могли бы делить их с помощью регулярки [^a-zA-Z].

2019-06-12 22:08 UTC, merged