Movies
RomE-HK/java-at-lessons pull request #6
Opened 2019-04-14 14:19 UTC by RomE-HK

Done

2019-04-15 06:52 UTC, AnnaS91 requested changes

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/Main.java
> +    public static void mainMenu() {
а зачем Вам пустой метод?

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/Main.java
> +    public static FilmsSet newCollection() {
в целом можно было бы и просто конструктор вызывать)

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/Main.java
> +        {
существует два подхода к оформлению открывающихся скобок - на той же строке, либо на новой. Но выбрать нужно только один. Раз у тебя везде на той же, поправь в этом методе

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Actor.java
> +    public Actor() {
не уверена, что для актера нужен контроллер без параметров, логичнее было бы оставить только конструктор с параметрами

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Actor.java
> +        builder.append(getFullName() + System.lineSeparator()); // ВОПРОС: ВЫЗОВ МЕТОДА ИЛИ ОБРАЩЕНИЕ К ПОЛЮ
не поняла вопроса

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +    public Film() {
аналогично

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +        /* if (isNameSurnameEmpty(name, surname)) {
можно в этом методе вообще было ожидать Actor и не думать о доп проверках

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +                if (actor.getFullName().contains(searchName) && actor.getFullName().contains(searchSurname)) {
довольно опасно, что если будет содержать часть имени и часть фамилии; почему не сравнить с getName() и getSurname()?

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +            System.out.println("There is no match for this title and year");
странное сообщение для такой проверки

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +    public void deleteActor(String name, String surname) {
можно было бы возвращать true или false в зависимости от успеха удаления

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +        //builder.append(filmCastToString() + System.lineSeparator());
лучше не оставлять закомментированный код

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/FilmsSet.java
> +public class FilmsSet implements Serializable {
можно не править в данной работе, но на будущее лучше выбирать названия, не связанные с деталями имплементации. Потом может возникнуть необходимость перейти от Set к List или Map и класс придется переименовывать. Можно было бы назвать, например, FilmLibrary

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/FilmsSet.java
> +        allFilms = new TreeSet<>();
а почему TreeSet?

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/FilmsSet.java
> +    public void deleteFilm(String title, int year) {
аналогично можно было бы возвращать boolean

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/test/java/epam/rome/moviescollection/MainTest.java
> +    public void serializeCollection() {
а что с наполнением?

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/test/java/epam/rome/moviescollection/model/ActorTest.java
> +        assertNotEquals(null, testActor.getSurname());
assertNotNull

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/test/java/epam/rome/moviescollection/model/FilmTest.java
> +        testFilm.addActor(newActor);        //ВОПРОС: НУЖНЫ ЛИ ТЕСТЫ ДЛЯ КОНСТРУКТОРА С ПАРАМЕТРАМИ?
в случае когда он просто инициализирует поля - нет, он покроется у Вас тестами за счёт вызова в других тестах. Если там какая-то крутая логика - да, нужны.

2019-04-15 06:52 UTC, AnnaS91 commented on moviesCollection/src/test/java/epam/rome/moviescollection/model/FilmsSetTest.java
> +    public void allFilmsByActor() {
allFilmsByActorTest

2019-04-15 14:49 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/Main.java
> +    public static void mainMenu() {
Это заготовка под интерфейс. Но раз он не обязателен, а достаточно классов, я его пока не стал дописывать, т.к. очень много времени ушло в прошлом задании на всю switch-case структуру

2019-04-15 14:52 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/Main.java
> +    public static void mainMenu() {
Там его вызов потому закомменчен в самом main

2019-04-15 14:54 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/Main.java
> +    public static FilmsSet newCollection() {
Я сюда изначально хотел прикрутить что-нибудь вроде проверки на существование уже имеющихся коллекций, с предложением загрузить одну из них. А вот если отказались, то тогда уже вызывать конструктор)

2019-04-15 14:55 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/Main.java
> +        {
Упс, не заметил

2019-04-15 14:56 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Actor.java
> +        builder.append(getFullName() + System.lineSeparator()); // ВОПРОС: ВЫЗОВ МЕТОДА ИЛИ ОБРАЩЕНИЕ К ПОЛЮ
Тут вопрос в том, как правльнее делать внутри класса: обращаться напрямую к полю экземпляра или вызывать метод дёргающий это поле?

2019-04-15 16:35 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Actor.java
> +        builder.append(getFullName() + System.lineSeparator()); // ВОПРОС: ВЫЗОВ МЕТОДА ИЛИ ОБРАЩЕНИЕ К ПОЛЮ
У вас же нет поля fullName, тут без вариантов. Для простых getterов проще к полю обратиться

2019-04-16 07:29 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Actor.java
> +        builder.append(getFullName() + System.lineSeparator()); // ВОПРОС: ВЫЗОВ МЕТОДА ИЛИ ОБРАЩЕНИЕ К ПОЛЮ
Ага, запомню. Спасибо.

2019-04-16 07:33 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +        /* if (isNameSurnameEmpty(name, surname)) {
Так ведь у меня уже есть метод, ожидающий Actor на входе. Это скорее просто альтернативный вариант, для добавления Актёра. Стоит убрать?

2019-04-16 07:36 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +                if (actor.getFullName().contains(searchName) && actor.getFullName().contains(searchSurname)) {
Есть подозрение, что писал это раньше момента, чем добавил getName() и getSurname(). Я сначала почему-то решил, что они мне не пригодятся)

2019-04-16 07:38 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +    public void deleteActor(String name, String surname) {
А. То есть это правильный подход?
Я просто что-то подобное делал в задачке с потоками, но там я стал в некоторых методах возвращать true и false, т.к. в тот момент не придумал другого способа проверить их работу)

2019-04-16 07:39 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +        //builder.append(filmCastToString() + System.lineSeparator());
Спасибо. Определялся, нужен ли мне этот вывод здесь
Fixed

2019-04-16 07:40 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/FilmsSet.java
> +public class FilmsSet implements Serializable {
Да я поправлю, думаю. Заодно потренируюсь в Идее общее переименование делать. Я всё время забываю, как оно там делается

2019-04-16 07:42 UTC, RomE-HK commented on moviesCollection/src/test/java/epam/rome/moviescollection/MainTest.java
> +    public void serializeCollection() {
А тут вопрос: как сериализацию от десериализации отдельно тестить если они связаны?

2019-04-16 07:42 UTC, RomE-HK commented on moviesCollection/src/test/java/epam/rome/moviescollection/model/FilmTest.java
> +        testFilm.addActor(newActor);        //ВОПРОС: НУЖНЫ ЛИ ТЕСТЫ ДЛЯ КОНСТРУКТОРА С ПАРАМЕТРАМИ?
Ага, понял

2019-04-16 07:43 UTC, RomE-HK commented on moviesCollection/src/test/java/epam/rome/moviescollection/model/FilmsSetTest.java
> +    public void allFilmsByActor() {
Fixed

2019-04-16 07:43 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/Main.java
> +        {
Fixed

2019-04-16 07:48 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Actor.java
> +    public Actor() {
Я их делал, чтобы можно было при тестировании коллекцию объектами набить, не прописывая каждый явно. Но по итогу, я решил так не делать, тем более, что для тестов хватает и пары тройки объектов, и эти контроллеры не пригодились

2019-04-16 07:48 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Actor.java
> +    public Actor() {
Fixed

2019-04-16 07:48 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +    public Film() {
Fixed

2019-04-16 07:53 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +            System.out.println("There is no match for this title and year");
Поправил)

2019-04-16 07:54 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +            System.out.println("There is no match for this title and year");
А сам метод лучше оставить в оригинальном виде или переписать так?
`if (!isNameSurnameEmpty(name, surname)) {
            Actor foundActor = getActor(name, surname);
            if (foundActor != null) {
                filmCast.remove(foundActor);
                return;
            }
        }
        System.out.println("Actor wasn't deleted!");`
Просто первый вариант кажется мне более наглядным, но и более длинным

2019-04-16 07:56 UTC, AnnaS91 commented on moviesCollection/src/test/java/epam/rome/moviescollection/MainTest.java
> +    public void serializeCollection() {
Сериализацию - можно протестировать отдельно, проверив, что файл создается, все дела. Дессериализацию - сериализуешь файл, считываешь и проверяешь наполнение

2019-04-16 07:57 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +            System.out.println("There is no match for this title and year");
А сам метод лучше оставить в оригинальном виде или переписать так?
`if (!isNameSurnameEmpty(name, surname)) {`
`    Actor foundActor = getActor(name, surname);`
`    if (foundActor != null) {`
`        filmCast.remove(foundActor);`
`        return;`
`    }`
`}`

Просто первый вариант кажется мне более наглядным, но и более длинным

2019-04-16 07:58 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +    public void deleteActor(String name, String surname) {
Отличный подход, используется во многих библиотеках. Стандартно либо возвращают boolean  cтатус, либо удаленный элемент

2019-04-16 07:59 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +            System.out.println("There is no match for this title and year");
Все отступы съелись(

2019-04-16 07:59 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +        /* if (isNameSurnameEmpty(name, surname)) {
можешь оставить, проглядела

2019-04-16 08:00 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +            System.out.println("There is no match for this title and year");
оставь первый, нет ничего плохого в длинных методах (если мы не говорим про сотни строк)

2019-04-16 11:30 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +        /* if (isNameSurnameEmpty(name, surname)) {
А проверки входных данных?

2019-04-16 11:31 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +            System.out.println("There is no match for this title and year");
Тоже так подумал. Просто смутило, что строки повторяются с выводом сообщения и return'ом

2019-04-16 11:33 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +    public void deleteActor(String name, String surname) {
Done

2019-04-16 11:34 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/FilmsSet.java
> +        allFilms = new TreeSet<>();
Чтобы фильмы в коллеции сразу сортировались по названиям

2019-04-16 11:36 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/FilmsSet.java
> +    public void deleteFilm(String title, int year) {
Done

2019-04-16 11:38 UTC, RomE-HK commented on moviesCollection/src/test/java/epam/rome/moviescollection/MainTest.java
> +    public void serializeCollection() {
А если файл у нас уже создан был ранее? Например, при прошлом входе в программу.
Тогда при неудачной сериализации у нас разве не останется файл на диске?

2019-04-16 11:44 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/FilmsSet.java
> +    public void deleteFilm(String title, int year) {
Тесты так же переписал

2019-04-16 11:44 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +    public void deleteActor(String name, String surname) {
Тесты так же переписал

2019-04-16 11:45 UTC, RomE-HK commented on moviesCollection/src/test/java/epam/rome/moviescollection/model/ActorTest.java
> +        assertNotEquals(null, testActor.getSurname());
Fixed

2019-04-17 13:31 UTC, RomE-HK commented on moviesCollection/src/test/java/epam/rome/moviescollection/MainTest.java
> +    public void serializeCollection() {
Ready

2019-04-17 13:31 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/model/Film.java
> +        /* if (isNameSurnameEmpty(name, surname)) {
Убрал их по итогу

2019-04-17 14:51 UTC, AnnaS91 requested changes

2019-04-17 14:51 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/Main.java
> +    static FilmsLibrary myCollection;
а почему всё без модификаторов доступа?

2019-04-17 14:51 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/Main.java
> +        {
тут тоже скобки стоит подправить

2019-04-18 09:23 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/Main.java
> +    static FilmsLibrary myCollection;
А default нам разве в Main'е не подходит?

2019-04-18 09:24 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/Main.java
> +        {
Fixed

2019-04-18 10:56 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/Main.java
> +    static FilmsLibrary myCollection;
Fixed
Указал private

2019-04-18 11:18 UTC, AnnaS91 commented on moviesCollection/src/main/java/epam/rome/moviescollection/Main.java
> +    static FilmsLibrary myCollection;
поля лучше всегда защищать

2019-04-18 11:20 UTC, RomE-HK commented on moviesCollection/src/main/java/epam/rome/moviescollection/Main.java
> +    static FilmsLibrary myCollection;
Хорошо, запомню. Спасибо

2019-04-18 11:26 UTC, AnnaS91 requested changes

2019-04-18 11:26 UTC, AnnaS91 commented on binaryIO/src/main/java/epam/rome/binaryio/BinaryIOFindKeyWords.java
> +    private static Map<String, Integer> map = new HashMap<String, Integer>();
мне очень не нравится название. В название лучше вообще не использовать типы и структуры,редкое исключение - составные имена. Глядя на переменную (или аргумент метода), пользователь должен понимать какую роль она играет (за что отвечает). map может отвечать за всё в этом мире :)

2019-04-18 11:26 UTC, AnnaS91 commented on binaryIO/src/main/java/epam/rome/binaryio/BinaryIOFindKeyWords.java
> +    public static void /*Map<String, Integer>*/ pullKeyWords(String filePath) {
раз уже решил переделать на поле, предыдущий вариант удаляй

2019-04-18 11:35 UTC, RomE-HK commented on binaryIO/src/main/java/epam/rome/binaryio/BinaryIOFindKeyWords.java
> +    private static Map<String, Integer> map = new HashMap<String, Integer>();
Упс! Тут примешались файлики из соседней ветки)
Это та же задачка на байтовые потомки что и ByteIO PR'е

2019-04-18 11:38 UTC, AnnaS91 commented on binaryIO/src/main/java/epam/rome/binaryio/BinaryIOFindKeyWords.java
> +    private static Map<String, Integer> map = new HashMap<String, Integer>();
ага, всё, я уже не понимаю, что я проверяю. Лучше конечно следить, чтобы не пересекались файлы. В таком случае эта задача тоже зачтена

2019-04-18 11:38 UTC, AnnaS91 approved these changes

2019-04-18 11:39 UTC, RomE-HK commented on binaryIO/src/main/java/epam/rome/binaryio/BinaryIOFindKeyWords.java
> +    public static void /*Map<String, Integer>*/ pullKeyWords(String filePath) {
Так, этого нету в ветке с ByteIO

2019-04-18 11:40 UTC, RomE-HK commented on binaryIO/src/main/java/epam/rome/binaryio/BinaryIOFindKeyWords.java
> +    private static Map<String, Integer> map = new HashMap<String, Integer>();
Да, я что-то напутал изначально при создании. Но map тогда всё же переименую

2019-06-12 22:13 UTC, merged